<?php
// Generated by ./dbgit db2file --export --tables=users,email_addresses,email_addr_bean_rel,acl_roles,acl_roles_users,securitygroups,securitygroups_users,wf_modules,wf_workflows,wf_statuses,wf_events
return array (
  0 => 
  array (
    'table' => 'acl_roles',
    'diff' => 
    array (
      0 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => 'Warehouse',
            'description' => '',
          ),
        ),
      ),
      1 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => 'Manager',
            'description' => '',
          ),
        ),
      ),
      2 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => 'Accounting',
            'description' => '',
          ),
        ),
      ),
    ),
  ),
  1 => 
  array (
    'table' => 'securitygroups',
    'diff' => 
    array (
      0 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => 'New-York',
            'description' => '',
            'noninheritable' => '0',
          ),
        ),
      ),
      1 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => 'London',
            'description' => '',
            'noninheritable' => '0',
          ),
        ),
      ),
    ),
  ),
  2 => 
  array (
    'table' => 'wf_modules',
    'diff' => 
    array (
      0 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => '',
            'description' => NULL,
            'wf_module' => 'Opportunities',
            'type_field' => 'opportunity_type',
          ),
        ),
      ),
    ),
  ),
  3 => 
  array (
    'table' => 'wf_workflows',
    'diff' => 
    array (
      0 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => 'Opportunities workflow',
            'description' => NULL,
            'wf_module' => 'Opportunities',
            'uniq_name' => 'opp_work',
            'status_field' => 'sales_stage',
            'bean_type' => '^^,^Existing Business^,^New Business^',
          ),
        ),
      ),
    ),
  ),
  4 => 
  array (
    'table' => 'wf_statuses',
    'diff' => 
    array (
      0 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => 'Accounting Confirm',
            'description' => NULL,
            'wf_module' => 'Opportunities',
            'uniq_name' => 'acc_confirm',
            'role_id' => 
            array (
              'name' => 'Accounting',
            ),
            'role2_id' => '',
            'edit_role_type' => 'nobody',
            'front_assigned_list_function' => 'DefaultUserList',
            'assigned_list_function' => 'DefaultUserList',
            'confirm_list_function' => 'DefaultUserList',
            'confirm_check_list_function' => 'OwnerUserList',
            'isfinal' => '0',
          ),
        ),
      ),
      1 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => 'Warehouse Confirm',
            'description' => NULL,
            'wf_module' => 'Opportunities',
            'uniq_name' => 'wh_confirm',
            'role_id' => 
            array (
              'name' => 'Warehouse',
            ),
            'role2_id' => '',
            'edit_role_type' => 'nobody',
            'front_assigned_list_function' => 'DefaultUserList',
            'assigned_list_function' => 'DefaultUserList',
            'confirm_list_function' => 'DefaultUserList',
            'confirm_check_list_function' => 'OwnerUserList',
            'isfinal' => '0',
          ),
        ),
      ),
      2 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => 'In work',
            'description' => NULL,
            'wf_module' => 'Opportunities',
            'uniq_name' => 'in_work',
            'role_id' => 
            array (
              'name' => 'Manager',
            ),
            'role2_id' => '',
            'edit_role_type' => 'nobody',
            'front_assigned_list_function' => 'DefaultUserList',
            'assigned_list_function' => 'DefaultUserList',
            'confirm_list_function' => 'DefaultUserList',
            'confirm_check_list_function' => 'OwnerUserList',
            'isfinal' => '0',
          ),
        ),
      ),
      3 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => 'Client Refusal',
            'description' => NULL,
            'wf_module' => 'Opportunities',
            'uniq_name' => 'client_refusal',
            'role_id' => 
            array (
              'name' => 'Manager',
            ),
            'role2_id' => '',
            'edit_role_type' => 'nobody',
            'front_assigned_list_function' => 'StatusAssignedDefaultUserList',
            'assigned_list_function' => 'DefaultUserList',
            'confirm_list_function' => 'DefaultUserList',
            'confirm_check_list_function' => 'OwnerUserList',
            'isfinal' => '1',
          ),
        ),
      ),
      4 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => 'New',
            'description' => NULL,
            'wf_module' => 'Opportunities',
            'uniq_name' => 'new',
            'role_id' => 
            array (
              'name' => 'Manager',
            ),
            'role2_id' => '',
            'edit_role_type' => 'owner',
            'front_assigned_list_function' => 'DefaultUserList',
            'assigned_list_function' => 'DefaultUserList',
            'confirm_list_function' => 'DefaultUserList',
            'confirm_check_list_function' => 'OwnerUserList',
            'isfinal' => '0',
          ),
        ),
      ),
      5 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => 'Completed',
            'description' => NULL,
            'wf_module' => 'Opportunities',
            'uniq_name' => 'completed',
            'role_id' => 
            array (
              'name' => 'Manager',
            ),
            'role2_id' => '',
            'edit_role_type' => 'nobody',
            'front_assigned_list_function' => 'StatusAssignedDefaultUserList',
            'assigned_list_function' => 'DefaultUserList',
            'confirm_list_function' => 'DefaultUserList',
            'confirm_check_list_function' => 'OwnerUserList',
            'isfinal' => '1',
          ),
        ),
      ),
    ),
  ),
  5 => 
  array (
    'table' => 'wf_events',
    'diff' => 
    array (
      0 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => '',
            'description' => NULL,
            'status1_id' => 
            array (
              'uniq_name' => 'acc_confirm',
              'wf_module' => 'Opportunities',
            ),
            'status2_id' => 
            array (
              'uniq_name' => 'completed',
              'wf_module' => 'Opportunities',
            ),
            'workflow_id' => 
            array (
              'uniq_name' => 'opp_work',
            ),
            'sort' => '100',
            'filter_function' => '',
            'validate_function' => NULL,
            'after_save' => NULL,
            'func_params' => '',
            'resolution_required' => '0',
          ),
        ),
      ),
      1 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => '',
            'description' => NULL,
            'status1_id' => '',
            'status2_id' => 
            array (
              'uniq_name' => 'new',
              'wf_module' => 'Opportunities',
            ),
            'workflow_id' => 
            array (
              'uniq_name' => 'opp_work',
            ),
            'sort' => '100',
            'filter_function' => '',
            'validate_function' => NULL,
            'after_save' => NULL,
            'func_params' => '',
            'resolution_required' => '0',
          ),
        ),
      ),
      2 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => '',
            'description' => NULL,
            'status1_id' => 
            array (
              'uniq_name' => 'in_work',
              'wf_module' => 'Opportunities',
            ),
            'status2_id' => 
            array (
              'uniq_name' => 'client_refusal',
              'wf_module' => 'Opportunities',
            ),
            'workflow_id' => 
            array (
              'uniq_name' => 'opp_work',
            ),
            'sort' => '200',
            'filter_function' => NULL,
            'validate_function' => NULL,
            'after_save' => NULL,
            'func_params' => NULL,
            'resolution_required' => '1',
          ),
        ),
      ),
      3 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => '',
            'description' => NULL,
            'status1_id' => 
            array (
              'uniq_name' => 'wh_confirm',
              'wf_module' => 'Opportunities',
            ),
            'status2_id' => 
            array (
              'uniq_name' => 'client_refusal',
              'wf_module' => 'Opportunities',
            ),
            'workflow_id' => 
            array (
              'uniq_name' => 'opp_work',
            ),
            'sort' => '200',
            'filter_function' => NULL,
            'validate_function' => NULL,
            'after_save' => NULL,
            'func_params' => NULL,
            'resolution_required' => '1',
          ),
        ),
      ),
      4 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => '',
            'description' => NULL,
            'status1_id' => 
            array (
              'uniq_name' => 'wh_confirm',
              'wf_module' => 'Opportunities',
            ),
            'status2_id' => 
            array (
              'uniq_name' => 'acc_confirm',
              'wf_module' => 'Opportunities',
            ),
            'workflow_id' => 
            array (
              'uniq_name' => 'opp_work',
            ),
            'sort' => '100',
            'filter_function' => '',
            'validate_function' => NULL,
            'after_save' => NULL,
            'func_params' => '',
            'resolution_required' => '0',
          ),
        ),
      ),
      5 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => '',
            'description' => NULL,
            'status1_id' => 
            array (
              'uniq_name' => 'new',
              'wf_module' => 'Opportunities',
            ),
            'status2_id' => 
            array (
              'uniq_name' => 'client_refusal',
              'wf_module' => 'Opportunities',
            ),
            'workflow_id' => 
            array (
              'uniq_name' => 'opp_work',
            ),
            'sort' => '200',
            'filter_function' => NULL,
            'validate_function' => NULL,
            'after_save' => NULL,
            'func_params' => NULL,
            'resolution_required' => '1',
          ),
        ),
      ),
      6 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => '',
            'description' => NULL,
            'status1_id' => 
            array (
              'uniq_name' => 'new',
              'wf_module' => 'Opportunities',
            ),
            'status2_id' => 
            array (
              'uniq_name' => 'in_work',
              'wf_module' => 'Opportunities',
            ),
            'workflow_id' => 
            array (
              'uniq_name' => 'opp_work',
            ),
            'sort' => '100',
            'filter_function' => '',
            'validate_function' => NULL,
            'after_save' => NULL,
            'func_params' => '',
            'resolution_required' => '0',
          ),
        ),
      ),
      7 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => '',
            'description' => NULL,
            'status1_id' => 
            array (
              'uniq_name' => 'in_work',
              'wf_module' => 'Opportunities',
            ),
            'status2_id' => 
            array (
              'uniq_name' => 'wh_confirm',
              'wf_module' => 'Opportunities',
            ),
            'workflow_id' => 
            array (
              'uniq_name' => 'opp_work',
            ),
            'sort' => '100',
            'filter_function' => '',
            'validate_function' => NULL,
            'after_save' => NULL,
            'func_params' => '',
            'resolution_required' => '0',
          ),
        ),
      ),
      8 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'name' => '',
            'description' => NULL,
            'status1_id' => 
            array (
              'uniq_name' => 'acc_confirm',
              'wf_module' => 'Opportunities',
            ),
            'status2_id' => 
            array (
              'uniq_name' => 'client_refusal',
              'wf_module' => 'Opportunities',
            ),
            'workflow_id' => 
            array (
              'uniq_name' => 'opp_work',
            ),
            'sort' => '200',
            'filter_function' => NULL,
            'validate_function' => NULL,
            'after_save' => NULL,
            'func_params' => NULL,
            'resolution_required' => '1',
          ),
        ),
      ),
    ),
  ),
  6 => 
  array (
    'table' => 'users',
    'diff' => 
    array (
      0 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'user_name' => 'test_wh2',
            'user_hash' => '46f94c8de14fb36680850768ff1b7f2a',
            'system_generated_password' => '0',
            'pwd_last_changed' => NULL,
            'authenticate_id' => NULL,
            'sugar_login' => '1',
            'first_name' => 'Darleen',
            'last_name' => 'Ainsley',
            'is_admin' => '0',
            'external_auth_only' => '0',
            'receive_notifications' => '1',
            'description' => NULL,
            'title' => NULL,
            'photo' => NULL,
            'department' => NULL,
            'phone_home' => NULL,
            'phone_mobile' => NULL,
            'phone_work' => NULL,
            'phone_other' => NULL,
            'phone_fax' => NULL,
            'status' => 'Active',
            'address_street' => NULL,
            'address_city' => NULL,
            'address_state' => NULL,
            'address_country' => NULL,
            'address_postalcode' => NULL,
            'portal_only' => '0',
            'show_on_employees' => '1',
            'employee_status' => 'Active',
            'messenger_id' => NULL,
            'messenger_type' => NULL,
            'reports_to_id' => '',
            'is_group' => '0',
            'factor_auth' => '0',
            'factor_auth_interface' => NULL,
          ),
        ),
      ),
      1 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'user_name' => 'test_wh1',
            'user_hash' => '46f94c8de14fb36680850768ff1b7f2a',
            'system_generated_password' => '0',
            'pwd_last_changed' => NULL,
            'authenticate_id' => NULL,
            'sugar_login' => '1',
            'first_name' => 'Isidore',
            'last_name' => 'Joseph',
            'is_admin' => '0',
            'external_auth_only' => '0',
            'receive_notifications' => '1',
            'description' => NULL,
            'title' => NULL,
            'photo' => NULL,
            'department' => NULL,
            'phone_home' => NULL,
            'phone_mobile' => NULL,
            'phone_work' => NULL,
            'phone_other' => NULL,
            'phone_fax' => NULL,
            'status' => 'Active',
            'address_street' => NULL,
            'address_city' => NULL,
            'address_state' => NULL,
            'address_country' => NULL,
            'address_postalcode' => NULL,
            'portal_only' => '0',
            'show_on_employees' => '1',
            'employee_status' => 'Active',
            'messenger_id' => NULL,
            'messenger_type' => NULL,
            'reports_to_id' => '',
            'is_group' => '0',
            'factor_auth' => '0',
            'factor_auth_interface' => NULL,
          ),
        ),
      ),
      2 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'user_name' => 'test_acc1',
            'user_hash' => '46f94c8de14fb36680850768ff1b7f2a',
            'system_generated_password' => '0',
            'pwd_last_changed' => NULL,
            'authenticate_id' => NULL,
            'sugar_login' => '1',
            'first_name' => 'Corrine',
            'last_name' => 'Dutch',
            'is_admin' => '0',
            'external_auth_only' => '0',
            'receive_notifications' => '1',
            'description' => NULL,
            'title' => NULL,
            'photo' => NULL,
            'department' => NULL,
            'phone_home' => NULL,
            'phone_mobile' => NULL,
            'phone_work' => NULL,
            'phone_other' => NULL,
            'phone_fax' => NULL,
            'status' => 'Active',
            'address_street' => NULL,
            'address_city' => NULL,
            'address_state' => NULL,
            'address_country' => NULL,
            'address_postalcode' => NULL,
            'portal_only' => '0',
            'show_on_employees' => '1',
            'employee_status' => 'Active',
            'messenger_id' => NULL,
            'messenger_type' => NULL,
            'reports_to_id' => '',
            'is_group' => '0',
            'factor_auth' => '0',
            'factor_auth_interface' => NULL,
          ),
        ),
      ),
      3 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'user_name' => 'test_m2',
            'user_hash' => '46f94c8de14fb36680850768ff1b7f2a',
            'system_generated_password' => '0',
            'pwd_last_changed' => NULL,
            'authenticate_id' => NULL,
            'sugar_login' => '1',
            'first_name' => 'Danny',
            'last_name' => 'Kingston',
            'is_admin' => '0',
            'external_auth_only' => '0',
            'receive_notifications' => '1',
            'description' => NULL,
            'title' => NULL,
            'photo' => NULL,
            'department' => NULL,
            'phone_home' => NULL,
            'phone_mobile' => NULL,
            'phone_work' => NULL,
            'phone_other' => NULL,
            'phone_fax' => NULL,
            'status' => 'Active',
            'address_street' => NULL,
            'address_city' => NULL,
            'address_state' => NULL,
            'address_country' => NULL,
            'address_postalcode' => NULL,
            'portal_only' => '0',
            'show_on_employees' => '1',
            'employee_status' => 'Active',
            'messenger_id' => NULL,
            'messenger_type' => NULL,
            'reports_to_id' => '',
            'is_group' => '0',
            'factor_auth' => '0',
            'factor_auth_interface' => NULL,
          ),
        ),
      ),
      4 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'user_name' => 'test_m1',
            'user_hash' => '46f94c8de14fb36680850768ff1b7f2a',
            'system_generated_password' => '0',
            'pwd_last_changed' => NULL,
            'authenticate_id' => NULL,
            'sugar_login' => '1',
            'first_name' => 'Alecia',
            'last_name' => 'Elfreda',
            'is_admin' => '0',
            'external_auth_only' => '0',
            'receive_notifications' => '1',
            'description' => NULL,
            'title' => NULL,
            'photo' => NULL,
            'department' => NULL,
            'phone_home' => NULL,
            'phone_mobile' => NULL,
            'phone_work' => NULL,
            'phone_other' => NULL,
            'phone_fax' => NULL,
            'status' => 'Active',
            'address_street' => NULL,
            'address_city' => NULL,
            'address_state' => NULL,
            'address_country' => NULL,
            'address_postalcode' => NULL,
            'portal_only' => '0',
            'show_on_employees' => '1',
            'employee_status' => 'Active',
            'messenger_id' => NULL,
            'messenger_type' => NULL,
            'reports_to_id' => '',
            'is_group' => '0',
            'factor_auth' => '0',
            'factor_auth_interface' => NULL,
          ),
        ),
      ),
      5 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'user_name' => 'test_acc2',
            'user_hash' => '46f94c8de14fb36680850768ff1b7f2a',
            'system_generated_password' => '0',
            'pwd_last_changed' => NULL,
            'authenticate_id' => NULL,
            'sugar_login' => '1',
            'first_name' => 'Petunia',
            'last_name' => 'Aurora',
            'is_admin' => '0',
            'external_auth_only' => '0',
            'receive_notifications' => '1',
            'description' => NULL,
            'title' => NULL,
            'photo' => NULL,
            'department' => NULL,
            'phone_home' => NULL,
            'phone_mobile' => NULL,
            'phone_work' => NULL,
            'phone_other' => NULL,
            'phone_fax' => NULL,
            'status' => 'Active',
            'address_street' => NULL,
            'address_city' => NULL,
            'address_state' => NULL,
            'address_country' => NULL,
            'address_postalcode' => NULL,
            'portal_only' => '0',
            'show_on_employees' => '1',
            'employee_status' => 'Active',
            'messenger_id' => NULL,
            'messenger_type' => NULL,
            'reports_to_id' => '',
            'is_group' => '0',
            'factor_auth' => '0',
            'factor_auth_interface' => NULL,
          ),
        ),
      ),
    ),
  ),
  7 => 
  array (
    'table' => 'email_addresses',
    'diff' => 
    array (
      0 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'email_address' => 'ainsleyd@test.hardsoft321.eu',
            'email_address_caps' => 'AINSLEYD@TEST.HARDSOFT321.EU',
            'invalid_email' => '0',
            'opt_out' => '0',
            'confirm_opt_in' => 'not-opt-in',
          ),
        ),
      ),
      1 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'email_address' => 'josephi@test.hardsoft321.eu',
            'email_address_caps' => 'JOSEPHI@TEST.HARDSOFT321.EU',
            'invalid_email' => '0',
            'opt_out' => '0',
            'confirm_opt_in' => 'not-opt-in',
          ),
        ),
      ),
      2 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'email_address' => 'dutchc@test.hardsoft321.eu',
            'email_address_caps' => 'DUTCHC@TEST.HARDSOFT321.EU',
            'invalid_email' => '0',
            'opt_out' => '0',
            'confirm_opt_in' => 'not-opt-in',
          ),
        ),
      ),
      3 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'email_address' => 'kingstond@test.hardsoft321.eu',
            'email_address_caps' => 'KINGSTOND@TEST.HARDSOFT321.EU',
            'invalid_email' => '0',
            'opt_out' => '0',
            'confirm_opt_in' => 'not-opt-in',
          ),
        ),
      ),
      4 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'email_address' => 'elfredaa@test.hardsoft321.eu',
            'email_address_caps' => 'ELFREDAA@TEST.HARDSOFT321.EU',
            'invalid_email' => '0',
            'opt_out' => '0',
            'confirm_opt_in' => 'not-opt-in',
          ),
        ),
      ),
      5 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'email_address' => 'aurorap@test.hardsoft321.eu',
            'email_address_caps' => 'AURORAP@TEST.HARDSOFT321.EU',
            'invalid_email' => '0',
            'opt_out' => '0',
            'confirm_opt_in' => 'not-opt-in',
          ),
        ),
      ),
    ),
  ),
  8 => 
  array (
    'table' => 'email_addr_bean_rel',
    'diff' => 
    array (
      0 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'email_address_id' => 
            array (
              'email_address' => 'ainsleyd@test.hardsoft321.eu',
            ),
            'bean_id' => 
            array (
              'user_name' => 'test_wh2',
            ),
            'bean_module' => 'Users',
            'primary_address' => '1',
            'reply_to_address' => '0',
          ),
        ),
      ),
      1 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'email_address_id' => 
            array (
              'email_address' => 'josephi@test.hardsoft321.eu',
            ),
            'bean_id' => 
            array (
              'user_name' => 'test_wh1',
            ),
            'bean_module' => 'Users',
            'primary_address' => '1',
            'reply_to_address' => '0',
          ),
        ),
      ),
      2 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'email_address_id' => 
            array (
              'email_address' => 'dutchc@test.hardsoft321.eu',
            ),
            'bean_id' => 
            array (
              'user_name' => 'test_acc1',
            ),
            'bean_module' => 'Users',
            'primary_address' => '1',
            'reply_to_address' => '0',
          ),
        ),
      ),
      3 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'email_address_id' => 
            array (
              'email_address' => 'kingstond@test.hardsoft321.eu',
            ),
            'bean_id' => 
            array (
              'user_name' => 'test_m2',
            ),
            'bean_module' => 'Users',
            'primary_address' => '1',
            'reply_to_address' => '0',
          ),
        ),
      ),
      4 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'email_address_id' => 
            array (
              'email_address' => 'elfredaa@test.hardsoft321.eu',
            ),
            'bean_id' => 
            array (
              'user_name' => 'test_m1',
            ),
            'bean_module' => 'Users',
            'primary_address' => '1',
            'reply_to_address' => '0',
          ),
        ),
      ),
      5 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'email_address_id' => 
            array (
              'email_address' => 'aurorap@test.hardsoft321.eu',
            ),
            'bean_id' => 
            array (
              'user_name' => 'test_acc2',
            ),
            'bean_module' => 'Users',
            'primary_address' => '1',
            'reply_to_address' => '0',
          ),
        ),
      ),
    ),
  ),
  9 => 
  array (
    'table' => 'acl_roles_users',
    'diff' => 
    array (
      0 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'role_id' => 
            array (
              'name' => 'Warehouse',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_wh2',
            ),
          ),
        ),
      ),
      1 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'role_id' => 
            array (
              'name' => 'Warehouse',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_wh1',
            ),
          ),
        ),
      ),
      2 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'role_id' => 
            array (
              'name' => 'Accounting',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_acc1',
            ),
          ),
        ),
      ),
      3 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'role_id' => 
            array (
              'name' => 'Manager',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_m2',
            ),
          ),
        ),
      ),
      4 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'role_id' => 
            array (
              'name' => 'Manager',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_m1',
            ),
          ),
        ),
      ),
      5 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'role_id' => 
            array (
              'name' => 'Accounting',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_acc2',
            ),
          ),
        ),
      ),
    ),
  ),
  10 => 
  array (
    'table' => 'securitygroups_users',
    'diff' => 
    array (
      0 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'securitygroup_id' => 
            array (
              'name' => 'New-York',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_wh2',
            ),
            'primary_group' => NULL,
            'noninheritable' => '0',
          ),
        ),
      ),
      1 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'securitygroup_id' => 
            array (
              'name' => 'London',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_wh2',
            ),
            'primary_group' => NULL,
            'noninheritable' => '0',
          ),
        ),
      ),
      2 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'securitygroup_id' => 
            array (
              'name' => 'New-York',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_wh1',
            ),
            'primary_group' => NULL,
            'noninheritable' => '0',
          ),
        ),
      ),
      3 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'securitygroup_id' => 
            array (
              'name' => 'New-York',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_acc1',
            ),
            'primary_group' => NULL,
            'noninheritable' => '0',
          ),
        ),
      ),
      4 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'securitygroup_id' => 
            array (
              'name' => 'New-York',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_m2',
            ),
            'primary_group' => NULL,
            'noninheritable' => '0',
          ),
        ),
      ),
      5 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'securitygroup_id' => 
            array (
              'name' => 'London',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_m2',
            ),
            'primary_group' => NULL,
            'noninheritable' => '0',
          ),
        ),
      ),
      6 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'securitygroup_id' => 
            array (
              'name' => 'New-York',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_m1',
            ),
            'primary_group' => NULL,
            'noninheritable' => '0',
          ),
        ),
      ),
      7 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'securitygroup_id' => 
            array (
              'name' => 'New-York',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_acc2',
            ),
            'primary_group' => NULL,
            'noninheritable' => '0',
          ),
        ),
      ),
      8 => 
      array (
        0 => 'add',
        1 => '',
        2 => 
        array (
          'data' => 
          array (
            'securitygroup_id' => 
            array (
              'name' => 'London',
            ),
            'user_id' => 
            array (
              'user_name' => 'test_acc2',
            ),
            'primary_group' => NULL,
            'noninheritable' => '0',
          ),
        ),
      ),
    ),
  ),
);
